apiVersion: apps/v1
kind: Deployment
metadata:
  name: sign-bridge-depl
spec:
  replicas: 2
  # Add rolling update strategy here
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%          # Maximum new pods created (over desired count)
      maxUnavailable: 25%    # Maximum pods unavailable during update
  selector:
    matchLabels:
      app: sign-bridge-depl
  template:
    metadata:
      labels:
        app: sign-bridge-depl
    spec:
      containers:
      - name: sign-bridge-depl
        image: mubaraklouis/signbridgebackend:v5
        resources:
          limits:
            memory: "128Mi"
            cpu: "225m"
        ports:
        - containerPort: 4000
  